repos:
  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
      - id: black
        exclude: ^reference/
        name: black
        language_version: python3.10
        args: ["--config=pyproject.toml"]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: ^reference/
        name: isort
        language_version: python3.10
        args: ["--settings-path=pyproject.toml"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        exclude: ^reference/
        language_version: python3.10
